<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:html="http://www.w3.org/TR/REC-html40"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
	xmlns:news="https://www.google.com/schemas/sitemap-news/0.9/"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
	<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
	<head>
		<title>XML Sitemap</title>
		<meta charset="utf-8" />
		<style>
			* {
				box-sizing: border-box;
			}
			body {
				font-family: system-ui, sans-serif;
			    font-size: .875rem;
			    line-height: 1.6;
			    color: oklch(0.439 0 0);
			    margin: 0 1rem;
			    text-align: center;
			}
			main {
				margin: 3rem auto;
				display: inline-block;
				text-align: left;
				max-width: 48rem;
			}
			h1 {
				text-align: center;
				line-height: 1;
				font-weight: 600;
			}
			.list {
				border: 1px solid oklch(0.922 0 0);
				border-radius: .25rem;
			}
			a {
				text-decoration: none;
				color: inherit;
			}
			a:hover {
				text-decoration: underline;
			}
			table {
				border-collapse: collapse;
				font-size: inherit;
			}
			tr:first-child {
			    border-bottom: 2px solid oklch(0.922 0 0);
			    background: none;
			}
			tr:nth-child(2n) {
			    background: oklch(0.97 0 0);
			}
			th,
			td {
			    padding: .5rem 1rem;
			}
			th {
				text-align: left;
				font-size: .75rem; 
				font-weight: normal;
				text-transform: uppercase;
			}
			.info {
				margin-top: 1rem;
			}
			.info a {
				text-decoration: underline;
			}
		</style>
	</head>
	<body>
	<main>
		<h1>XML Sitemap</h1>

		<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
			<div class="list">
				<table width="100%">
					<tr>
						<th width="100%">Sitemap</th>
					</tr>
					<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
						<xsl:variable name="sitemapURL">
							<xsl:value-of select="sitemap:loc"/>
						</xsl:variable>
						<tr>
							<td>
								<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
							</td>
						</tr>
					</xsl:for-each>
				</table>
			</div>
			<div class="info">
				This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps. Generated by <a href="https://wpslimseo.com">Slim SEO</a>.
			</div>
		</xsl:if>

		<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
			<div class="list">
				<table>
					<tr>
						<th width="75%">URL</th>
						<th width="25%">Last Modified</th>
					</tr>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td>
								<xsl:variable name="itemURL">
									<xsl:value-of select="sitemap:loc"/>
								</xsl:variable>
								<a href="{$itemURL}">
									<xsl:value-of select="sitemap:loc"/>
								</a>
							</td>
							<td>
								<xsl:value-of select="sitemap:lastmod"/>
							</td>
						</tr>
					</xsl:for-each>
				</table>
			</div>
			<div class="info">
				This XML Sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs. Generated by <a href="https://wpslimseo.com">Slim SEO</a>.
			</div>
		</xsl:if>
	</main>
	</body>
	</html>
</xsl:template>
</xsl:stylesheet>
